{% set version = "12.4.0" %}

package:
  name: cuda-libraries-dev
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-cudart-dev 12.4.99
    - cuda-cccl 12.4.99
    - cuda-profiler-api 12.4.99
    - cuda-driver-dev 12.4.99    # [linux]
    - cuda-nvrtc-dev 12.4.99
    - cuda-opencl-dev 12.4.99    # [linux64 or win]
    - libcublas-dev 12.4.2.65
    - libcufft-dev 11.2.0.44
    - libcufile-dev 1.9.0.20       # [linux64 or aarch64]
    - libcurand-dev 10.3.5.119
    - libcusolver-dev 11.6.0.99
    - libcusparse-dev 12.3.0.142
    - libnpp-dev 12.2.5.2
    - libnvfatbin-dev 12.4.99
    - libnvjitlink-dev 12.4.99
    - libnvjpeg-dev 12.3.1.89

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library development packages.
  description: |
    Meta-package containing all available library development packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
