{% set version = "12.2.2" %}

package:
  name: cuda-libraries-dev
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-cudart-dev 12.2.140
    - cuda-cccl 12.2.140
    - cuda-profiler-api 12.2.140
    - cuda-driver-dev 12.2.140  # [linux]
    - cuda-nvrtc-dev 12.2.140
    - cuda-opencl-dev 12.2.140   # [linux64 or win]
    - libcublas-dev 12.2.5.6
    - libcufft-dev 11.0.8.103
    - libcufile-dev 1.7.2.10    # [linux64 or aarch64]
    - libcurand-dev 10.3.3.141
    - libcusolver-dev 11.5.2.141
    - libcusparse-dev 12.1.2.141
    - libnpp-dev 12.2.1.4
    - libnvjitlink-dev 12.2.140
    - libnvjpeg-dev 12.2.2.4

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library development packages.
  description: |
    Meta-package containing all available library development packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
