{% set version = "12.1.1" %}

package:
  name: cuda-libraries-dev
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: 5db25d4fd138013b563f9a3d1d87f7de7df1dac014fd4cccdfbb3435a5cff761

build:
  number: 0
  skip: true  # [osx]

requirements:
  run:
    - cuda-cudart-dev 12.1.105
    - cuda-cccl 12.1.109
    - cuda-profiler-api 12.1.105
    - cuda-driver-dev 12.1.105  # [linux]
    - cuda-nvrtc-dev 12.1.105
    - cuda-opencl-dev 12.1.105   # [linux64 or win]
    - libcublas-dev 12.1.3.1
    - libcufft-dev 11.0.2.54
    - libcufile-dev 1.6.1.9    # [linux64]
    - libcurand-dev 10.3.2.106
    - libcusolver-dev 11.4.5.107
    - libcusparse-dev 12.1.0.106
    - libnpp-dev 12.1.0.40
    - libnvjitlink-dev 12.1.105
    - libnvjpeg-dev 12.2.0.2

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Meta-package containing all available library development packages.
  description: |
    Meta-package containing all available library development packages.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
